### ISSUE TITLE
Can you provide some instructions on how to download and organize the activitynet dataset?

### ISSUE THREAD

**Issue by qwangku** [MCG-NJU/OCSampler#1]
Thanks for sharing this great work.
I got 404 error from https://github.com/open-mmlab/mmaction2/blob/master/docs/data_preparation.md

I am running `bash tools/dist_train.sh configs/activitynet_10to6_resnet50.py 8 --validate` and got the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/ActivityNet/anet_320p_frames/v_nuEK3POl9jA/img_00107.jpg'`

Could you please share some instructions on how to get net_320p_frames?

**Comment by dreamerlin** [comment]
It seems that the link is updated: https://github.com/open-mmlab/mmaction2/blob/master/docs/en/data_preparation.md
